### PR TITLE
Update compiled-grammar.js

### PR DESCRIPTION
**Pull request by mstijak**
This label was causing a browser error in a webpack generated bundle, so I removed it as it's not referenced anywhere else in the file.
I know that the file is generated, but I don't know how to fix it properly.

Btw, great library. I really like that it doesn't try to be your router. :+1:

### CODE REVIEW

**Comment by rcs** [comment]
Thanks! could you give me a bit more detail on where you were seeing errors? I'd like at least understand what problem this is causing, even if I can't fix the toolchain for it.

Maybe we can figure that out and come up with a different way to work around it. To get this fixed in this way (changing the compiled file), we'll need to update the `compile-parser` execution path _somehow_, so this doesn't get lost and reintroduced when the grammar gets updated.

**Comment by rcs** [comment]
Looking into this more, https://github.com/zaach/jison/pull/305 looks rather promising. When I get a chance, i'll try updating there, or will accept a PR for it.

**Comment by mstijak** [comment]
You're right. Updating jison to the latest version did the trick. 
If you decide to merge this, please also publish a new version on npm.

**Comment by rcs** [comment]
Would you mind squashing these two commits down to one? I'll merge and cut a new version.

Thank you!

**Comment by mstijak** [comment]
I made a new pull request #14 .

**Pull request closed without merging**
